#ifdef __CINT__

#pragma link off all globals;
#pragma link off all classes;
#pragma link off all functions;

#pragma link C++ nestedclass;
#pragma link C++ nestedtypedef;
#pragma link C++ namespace Decoder;

#pragma link C++ class TriBCM+;
#pragma link C++ class Decoder::VETROCtdcModule+;
#pragma link C++ class Decoder::TstF1TDCModule+;
#pragma link C++ class TdcDataEvtHandler+;
#pragma link C++ class TriFadcCherenkov+;
#pragma link C++ class TriFadcAerogelC+;
#pragma link C++ class TriFadcRasteredBeam+;
#pragma link C++ class TriFadcRaster+;
#pragma link C++ class TriFadcBPM+;
#pragma link C++ class TriFadcScin+;
//#pragma link C++ class TriFadcScin::DataDest+;
#pragma link C++ class TriFadcScinF1+;
//#pragma link C++ class TriFadcScinF1::DataDest+;
#pragma link C++ class TriFadcShower+;
#pragma link C++ class TriFadcUnRasteredBeam+;
#pragma link C++ class TriFadcXscin+;
//#pragma link C++ class TriFadcXscin::DataDest+;
#pragma link C++ class TriHRS+;
#pragma link C++ class TriSpectrometer+;
#pragma link C++ class TriSpectrometerDetector+;
#pragma link C++ class TriTrackingDetector+;
#pragma link C++ class TriVDC+;
#pragma link C++ class TriVDCPlane+;
#pragma link C++ class TriVDCUVPlane+;
#pragma link C++ class TriVDCPlane+;
#pragma link C++ class TriVDCUVTrack+;
#pragma link C++ class TriVDCCluster+;
#pragma link C++ class TriVDCHit+;
#pragma link C++ class TriVDCTimeToDistConv+;
#pragma link C++ class TriTrackInfo+;
#pragma link C++ class TriTrackingModule+;
#pragma link C++ class TriNonTrackingDetector+;
#pragma link C++ class TriScintillator+;
//#pragma link C++ class TriScintillator::DataDest+;
#pragma link C++ class TriXscin+;
//#pragma link C++ class TriXscin::DataDest+;
#pragma link C++ class TriTrack+;
#pragma link C++ class TriVDCTrackPair+;
#pragma link C++ class TriVDCTrackID+;
#pragma link C++ class TriTrackID+;
#pragma link C++ class TriVDCWire+;
#pragma link C++ class TriVDCAnalyticTTDConv+;
#pragma link C++ class TriTriggerTime+;
#pragma link C++ class TriTrackProj+;
#pragma link C++ class TriScalerEvtHandler+;
#pragma link C++ class Decoder::V1495Module+;
#pragma link C++ class ClockCountEvtHandler+;
#pragma link C++ class TriVDCeff+;
#pragma link C++ class Tri_Beam_Eloss+;
#pragma link C++ class Tri_ElossCorrection+;
#pragma link C++ class Tri_Track_Eloss+;
#pragma link C++ class Tritium_Beam_Eloss+;
#pragma link C++ class Tritium_THaScaler100EvtHandler+;
#pragma link C++ class Tritium_HRS+;
#pragma link C++ class Tritium_TSScaler+;
#pragma link C++ class Tritium_Track_Eloss+;
#pragma link C++ class Tritium_Xscin+;
//#pragma link C++ class Tritium_Xscin::DataDest+;

#endif
